Add missing file to source and wheel distribution
Both the source and wheel distributions on PyPi are missing the
`extension-schemas.json` file.

```
FileNotFoundError: [Errno 2] No such file or directory: '.../venv/lib/python3.8/site-packages/openapi_sqlalchemy/helpers/get_ext_prop/extension-schemas.json'
````